// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzgmKhSoc6CXWYtl5gI0g5dX2jBBXU_fA',
    appId: '1:656694233391:web:42dd90f5de64cab37c39da',
    messagingSenderId: '656694233391',
    projectId: 'iptv-2ab34',
    authDomain: 'iptv-2ab34.firebaseapp.com',
    storageBucket: 'iptv-2ab34.firebasestorage.app',
    measurementId: 'G-5WHQJ7EW75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9LEsGOn2vtvH8UdSy1Js39jbhCo853sc',
    appId: '1:656694233391:android:208d6e480e91e1a67c39da',
    messagingSenderId: '656694233391',
    projectId: 'iptv-2ab34',
    storageBucket: 'iptv-2ab34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwVrBeaij4bBMko8pOM6BdpEhTGV6BbWs',
    appId: '1:656694233391:ios:46418067484f799a7c39da',
    messagingSenderId: '656694233391',
    projectId: 'iptv-2ab34',
    storageBucket: 'iptv-2ab34.firebasestorage.app',
    iosClientId: '656694233391-3h0pp8ccmr1kci6smnoe1jr3tusaecd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwVrBeaij4bBMko8pOM6BdpEhTGV6BbWs',
    appId: '1:656694233391:ios:46418067484f799a7c39da',
    messagingSenderId: '656694233391',
    projectId: 'iptv-2ab34',
    storageBucket: 'iptv-2ab34.firebasestorage.app',
    iosClientId: '656694233391-3h0pp8ccmr1kci6smnoe1jr3tusaecd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzgmKhSoc6CXWYtl5gI0g5dX2jBBXU_fA',
    appId: '1:656694233391:web:33458af8fd97d8f87c39da',
    messagingSenderId: '656694233391',
    projectId: 'iptv-2ab34',
    authDomain: 'iptv-2ab34.firebaseapp.com',
    storageBucket: 'iptv-2ab34.firebasestorage.app',
    measurementId: 'G-T13SKCQHHS',
  );
}
