// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/category.dart';
import 'models/channel.dart';
import 'models/epg_channel_info.dart';
import 'models/movie.dart';
import 'models/playlist.dart';
import 'models/tv_episode.dart';
import 'models/tv_program.dart';
import 'models/tv_series.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6929368120627354406),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(4, 4745913920730535520),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 191390281272516914),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2803780937146385661),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5067209142868406790),
        name: 'playlistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 465281871145453932),
        relationTarget: 'Playlist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4745913920730535520),
        name: 'contentType',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'channels',
        srcEntity: 'Channel',
        srcField: 'category',
      ),
      obx_int.ModelBacklink(
        name: 'movies',
        srcEntity: 'Movie',
        srcField: 'category',
      ),
      obx_int.ModelBacklink(
        name: 'tvSeries',
        srcEntity: 'TvSeries',
        srcField: 'category',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8928010406012741024),
    name: 'Channel',
    lastPropertyId: const obx_int.IdUid(7, 6823280508314365194),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5396832591853593847),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4375596590147557855),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9202326721170087737),
        name: 'streamUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4417154303805475116),
        name: 'logoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4866518405179625168),
        name: 'epgId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4435866022832771261),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 6298170325127174470),
        relationTarget: 'Category',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6823280508314365194),
        name: 'playlistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4804884647129120771),
        relationTarget: 'Playlist',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1589148947862671018),
    name: 'Playlist',
    lastPropertyId: const obx_int.IdUid(8, 4441341921410104738),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1479578575740980232),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4126653522124223693),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 797288597223681108),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1295628664668431169),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4686404077635627352),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1586444713288330113),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4441341921410104738),
        name: 'typeInt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'channels',
        srcEntity: 'Channel',
        srcField: 'playlist',
      ),
      obx_int.ModelBacklink(
        name: 'categories',
        srcEntity: 'Category',
        srcField: 'playlist',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7285596459614028247),
    name: 'Movie',
    lastPropertyId: const obx_int.IdUid(20, 7558253799388110153),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2173300897580892181),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 683405520262835527),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8289653683684821476),
        name: 'streamUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 665641816611066225),
        name: 'coverUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3305389454735302271),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7653404047497942149),
        name: 'year',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1629763343334552293),
        name: 'duration',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 890482566908287578),
        name: 'rating',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5181229339734790911),
        name: 'streamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8055541616763388276),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 7530664368021115429),
        relationTarget: 'Category',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8402733163535034087),
        name: 'playlistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 1141124170263337572),
        relationTarget: 'Playlist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6282617763145604509),
        name: 'tmdbId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7211319173569484390),
        name: 'trailer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4160177569972397559),
        name: 'added',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1692480152779986244),
        name: 'rating_5based',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 567249796450363336),
        name: 'posterUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6667078932682744026),
        name: 'backdropUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7838675007446937760),
        name: 'myList',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 878464207708610030),
        name: 'isFeatured',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 7558253799388110153),
        name: 'featuredPosterUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 112040778544591343),
    name: 'TvEpisode',
    lastPropertyId: const obx_int.IdUid(10, 1384756934297365368),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2314172188130513527),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8624157076548749818),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4057592860291107675),
        name: 'streamUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4573254634253683310),
        name: 'seasonNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4442701472099668992),
        name: 'episodeNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4360154553846235579),
        name: 'coverUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8509861850733897903),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5132917754772488849),
        name: 'duration',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8416825916432125647),
        name: 'streamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1384756934297365368),
        name: 'seriesId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 7773165134321269333),
        relationTarget: 'TvSeries',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4381905975208352576),
    name: 'TvSeries',
    lastPropertyId: const obx_int.IdUid(13, 450788826881780348),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 224508400378006622),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5618292735369800495),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1818067329146686583),
        name: 'coverUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8604353432324590425),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3846629650222258849),
        name: 'year',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5167234966095862339),
        name: 'rating',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6948544970790557341),
        name: 'seriesId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3654151929488537858),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 8449771543881811760),
        relationTarget: 'Category',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7785102120040485257),
        name: 'playlistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 4248628634840899570),
        relationTarget: 'Playlist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2739829902393060728),
        name: 'tmdbId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7294473990937461405),
        name: 'myList',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7984307903677311933),
        name: 'isFeatured',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 450788826881780348),
        name: 'featuredPosterUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'episodes',
        srcEntity: 'TvEpisode',
        srcField: 'series',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 8557467261400270990),
    name: 'EpgChannelInfo',
    lastPropertyId: const obx_int.IdUid(4, 5468249262399665047),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 94372922698955013),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6384017336063810301),
        name: 'xmlTvId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 6058583542607390521),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1297958449039772196),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5468249262399665047),
        name: 'iconUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 3456862542921013776),
    name: 'TvProgram',
    lastPropertyId: const obx_int.IdUid(6, 3384765055618164560),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9182398847096650432),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 879429844366273503),
        name: 'channelXmlTvId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 8146096163909404869),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4220292751474022412),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5639544347299011667),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7542204186001361067),
        name: 'startTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3384765055618164560),
        name: 'stopTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 3456862542921013776),
    lastIndexId: const obx_int.IdUid(10, 8146096163909404869),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [1150967270605485312],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[0],
      toOneRelations: (Category object) => [object.playlist],
      toManyRelations:
          (Category object) => {
            obx_int.RelInfo<Channel>.toOneBacklink(
                  6,
                  object.id,
                  (Channel srcObject) => srcObject.category,
                ):
                object.channels,
            obx_int.RelInfo<Movie>.toOneBacklink(
                  10,
                  object.id,
                  (Movie srcObject) => srcObject.category,
                ):
                object.movies,
            obx_int.RelInfo<TvSeries>.toOneBacklink(
                  8,
                  object.id,
                  (TvSeries srcObject) => srcObject.category,
                ):
                object.tvSeries,
          },
      getId: (Category object) => object.id,
      setId: (Category object, int id) {
        object.id = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.playlist.targetId);
        fbb.addInt64(3, object.contentType);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = Category(name: nameParam, contentType: contentTypeParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.playlist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.playlist.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Category>(
          object.channels,
          store,
          obx_int.RelInfo<Channel>.toOneBacklink(
            6,
            object.id,
            (Channel srcObject) => srcObject.category,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Category>(
          object.movies,
          store,
          obx_int.RelInfo<Movie>.toOneBacklink(
            10,
            object.id,
            (Movie srcObject) => srcObject.category,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Category>(
          object.tvSeries,
          store,
          obx_int.RelInfo<TvSeries>.toOneBacklink(
            8,
            object.id,
            (TvSeries srcObject) => srcObject.category,
          ),
        );
        return object;
      },
    ),
    Channel: obx_int.EntityDefinition<Channel>(
      model: _entities[1],
      toOneRelations: (Channel object) => [object.category, object.playlist],
      toManyRelations: (Channel object) => {},
      getId: (Channel object) => object.id,
      setId: (Channel object, int id) {
        object.id = id;
      },
      objectToFB: (Channel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final streamUrlOffset = fbb.writeString(object.streamUrl);
        final logoUrlOffset =
            object.logoUrl == null ? null : fbb.writeString(object.logoUrl!);
        final epgIdOffset =
            object.epgId == null ? null : fbb.writeString(object.epgId!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, streamUrlOffset);
        fbb.addOffset(3, logoUrlOffset);
        fbb.addOffset(4, epgIdOffset);
        fbb.addInt64(5, object.category.targetId);
        fbb.addInt64(6, object.playlist.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final streamUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final logoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final epgIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = Channel(
          name: nameParam,
          streamUrl: streamUrlParam,
          logoUrl: logoUrlParam,
          epgId: epgIdParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.category.attach(store);
        object.playlist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.playlist.attach(store);
        return object;
      },
    ),
    Playlist: obx_int.EntityDefinition<Playlist>(
      model: _entities[2],
      toOneRelations: (Playlist object) => [],
      toManyRelations:
          (Playlist object) => {
            obx_int.RelInfo<Channel>.toOneBacklink(
                  7,
                  object.id,
                  (Channel srcObject) => srcObject.playlist,
                ):
                object.channels,
            obx_int.RelInfo<Category>.toOneBacklink(
                  3,
                  object.id,
                  (Category srcObject) => srcObject.playlist,
                ):
                object.categories,
          },
      getId: (Playlist object) => object.id,
      setId: (Playlist object, int id) {
        object.id = id;
      },
      objectToFB: (Playlist object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final urlOffset = fbb.writeString(object.url);
        final usernameOffset =
            object.username == null ? null : fbb.writeString(object.username!);
        final passwordOffset =
            object.password == null ? null : fbb.writeString(object.password!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, urlOffset);
        fbb.addOffset(3, usernameOffset);
        fbb.addOffset(4, passwordOffset);
        fbb.addInt64(6, object.lastUpdated.millisecondsSinceEpoch);
        fbb.addInt64(7, object.typeInt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final passwordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final typeIntParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = Playlist(
          name: nameParam,
          url: urlParam,
          username: usernameParam,
          password: passwordParam,
          typeInt: typeIntParam,
          lastUpdated: lastUpdatedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<Playlist>(
          object.channels,
          store,
          obx_int.RelInfo<Channel>.toOneBacklink(
            7,
            object.id,
            (Channel srcObject) => srcObject.playlist,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Playlist>(
          object.categories,
          store,
          obx_int.RelInfo<Category>.toOneBacklink(
            3,
            object.id,
            (Category srcObject) => srcObject.playlist,
          ),
        );
        return object;
      },
    ),
    Movie: obx_int.EntityDefinition<Movie>(
      model: _entities[3],
      toOneRelations: (Movie object) => [object.category, object.playlist],
      toManyRelations: (Movie object) => {},
      getId: (Movie object) => object.id,
      setId: (Movie object, int id) {
        object.id = id;
      },
      objectToFB: (Movie object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final streamUrlOffset = fbb.writeString(object.streamUrl);
        final coverUrlOffset =
            object.coverUrl == null ? null : fbb.writeString(object.coverUrl!);
        final descriptionOffset =
            object.description == null
                ? null
                : fbb.writeString(object.description!);
        final yearOffset =
            object.year == null ? null : fbb.writeString(object.year!);
        final durationOffset =
            object.duration == null ? null : fbb.writeString(object.duration!);
        final ratingOffset =
            object.rating == null ? null : fbb.writeString(object.rating!);
        final streamIdOffset =
            object.streamId == null ? null : fbb.writeString(object.streamId!);
        final tmdbIdOffset =
            object.tmdbId == null ? null : fbb.writeString(object.tmdbId!);
        final trailerOffset =
            object.trailer == null ? null : fbb.writeString(object.trailer!);
        final addedOffset =
            object.added == null ? null : fbb.writeString(object.added!);
        final posterUrlOffset =
            object.posterUrl == null
                ? null
                : fbb.writeString(object.posterUrl!);
        final backdropUrlOffset =
            object.backdropUrl == null
                ? null
                : fbb.writeString(object.backdropUrl!);
        final featuredPosterUrlOffset =
            object.featuredPosterUrl == null
                ? null
                : fbb.writeString(object.featuredPosterUrl!);
        fbb.startTable(21);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, streamUrlOffset);
        fbb.addOffset(3, coverUrlOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, yearOffset);
        fbb.addOffset(6, durationOffset);
        fbb.addOffset(7, ratingOffset);
        fbb.addOffset(8, streamIdOffset);
        fbb.addInt64(9, object.category.targetId);
        fbb.addInt64(10, object.playlist.targetId);
        fbb.addOffset(11, tmdbIdOffset);
        fbb.addOffset(12, trailerOffset);
        fbb.addOffset(13, addedOffset);
        fbb.addFloat64(14, object.rating_5based);
        fbb.addOffset(15, posterUrlOffset);
        fbb.addOffset(16, backdropUrlOffset);
        fbb.addInt64(17, object.myList);
        fbb.addBool(18, object.isFeatured);
        fbb.addOffset(19, featuredPosterUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final streamUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final coverUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final yearParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final durationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final ratingParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final streamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final tmdbIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final posterUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final backdropUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final featuredPosterUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final trailerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final addedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final rating_5basedParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final myListParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          38,
        );
        final isFeaturedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          40,
          false,
        );
        final object = Movie(
          name: nameParam,
          streamUrl: streamUrlParam,
          coverUrl: coverUrlParam,
          description: descriptionParam,
          year: yearParam,
          duration: durationParam,
          rating: ratingParam,
          streamId: streamIdParam,
          tmdbId: tmdbIdParam,
          posterUrl: posterUrlParam,
          backdropUrl: backdropUrlParam,
          featuredPosterUrl: featuredPosterUrlParam,
          trailer: trailerParam,
          added: addedParam,
          rating_5based: rating_5basedParam,
          myList: myListParam,
          isFeatured: isFeaturedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.category.attach(store);
        object.playlist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.playlist.attach(store);
        return object;
      },
    ),
    TvEpisode: obx_int.EntityDefinition<TvEpisode>(
      model: _entities[4],
      toOneRelations: (TvEpisode object) => [object.series],
      toManyRelations: (TvEpisode object) => {},
      getId: (TvEpisode object) => object.id,
      setId: (TvEpisode object, int id) {
        object.id = id;
      },
      objectToFB: (TvEpisode object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final streamUrlOffset = fbb.writeString(object.streamUrl);
        final coverUrlOffset =
            object.coverUrl == null ? null : fbb.writeString(object.coverUrl!);
        final descriptionOffset =
            object.description == null
                ? null
                : fbb.writeString(object.description!);
        final durationOffset =
            object.duration == null ? null : fbb.writeString(object.duration!);
        final streamIdOffset =
            object.streamId == null ? null : fbb.writeString(object.streamId!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, streamUrlOffset);
        fbb.addInt64(3, object.seasonNumber);
        fbb.addInt64(4, object.episodeNumber);
        fbb.addOffset(5, coverUrlOffset);
        fbb.addOffset(6, descriptionOffset);
        fbb.addOffset(7, durationOffset);
        fbb.addOffset(8, streamIdOffset);
        fbb.addInt64(9, object.series.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final streamUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final seasonNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final episodeNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final coverUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final durationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final streamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = TvEpisode(
          title: titleParam,
          streamUrl: streamUrlParam,
          seasonNumber: seasonNumberParam,
          episodeNumber: episodeNumberParam,
          coverUrl: coverUrlParam,
          description: descriptionParam,
          duration: durationParam,
          streamId: streamIdParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.series.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.series.attach(store);
        return object;
      },
    ),
    TvSeries: obx_int.EntityDefinition<TvSeries>(
      model: _entities[5],
      toOneRelations: (TvSeries object) => [object.category, object.playlist],
      toManyRelations:
          (TvSeries object) => {
            obx_int.RelInfo<TvEpisode>.toOneBacklink(
                  10,
                  object.id,
                  (TvEpisode srcObject) => srcObject.series,
                ):
                object.episodes,
          },
      getId: (TvSeries object) => object.id,
      setId: (TvSeries object, int id) {
        object.id = id;
      },
      objectToFB: (TvSeries object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final coverUrlOffset =
            object.coverUrl == null ? null : fbb.writeString(object.coverUrl!);
        final descriptionOffset =
            object.description == null
                ? null
                : fbb.writeString(object.description!);
        final yearOffset =
            object.year == null ? null : fbb.writeString(object.year!);
        final ratingOffset =
            object.rating == null ? null : fbb.writeString(object.rating!);
        final seriesIdOffset =
            object.seriesId == null ? null : fbb.writeString(object.seriesId!);
        final tmdbIdOffset =
            object.tmdbId == null ? null : fbb.writeString(object.tmdbId!);
        final featuredPosterUrlOffset =
            object.featuredPosterUrl == null
                ? null
                : fbb.writeString(object.featuredPosterUrl!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, coverUrlOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, yearOffset);
        fbb.addOffset(5, ratingOffset);
        fbb.addOffset(6, seriesIdOffset);
        fbb.addInt64(7, object.category.targetId);
        fbb.addInt64(8, object.playlist.targetId);
        fbb.addOffset(9, tmdbIdOffset);
        fbb.addInt64(10, object.myList);
        fbb.addBool(11, object.isFeatured);
        fbb.addOffset(12, featuredPosterUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final coverUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final yearParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final ratingParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final seriesIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final tmdbIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final myListParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final isFeaturedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final featuredPosterUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final object = TvSeries(
          name: nameParam,
          coverUrl: coverUrlParam,
          description: descriptionParam,
          year: yearParam,
          rating: ratingParam,
          seriesId: seriesIdParam,
          tmdbId: tmdbIdParam,
          myList: myListParam,
          isFeatured: isFeaturedParam,
          featuredPosterUrl: featuredPosterUrlParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.category.attach(store);
        object.playlist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.playlist.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<TvSeries>(
          object.episodes,
          store,
          obx_int.RelInfo<TvEpisode>.toOneBacklink(
            10,
            object.id,
            (TvEpisode srcObject) => srcObject.series,
          ),
        );
        return object;
      },
    ),
    EpgChannelInfo: obx_int.EntityDefinition<EpgChannelInfo>(
      model: _entities[6],
      toOneRelations: (EpgChannelInfo object) => [],
      toManyRelations: (EpgChannelInfo object) => {},
      getId: (EpgChannelInfo object) => object.id,
      setId: (EpgChannelInfo object, int id) {
        object.id = id;
      },
      objectToFB: (EpgChannelInfo object, fb.Builder fbb) {
        final xmlTvIdOffset = fbb.writeString(object.xmlTvId);
        final displayNameOffset = fbb.writeString(object.displayName);
        final iconUrlOffset =
            object.iconUrl == null ? null : fbb.writeString(object.iconUrl!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, xmlTvIdOffset);
        fbb.addOffset(2, displayNameOffset);
        fbb.addOffset(3, iconUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final xmlTvIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final displayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final iconUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = EpgChannelInfo(
          id: idParam,
          xmlTvId: xmlTvIdParam,
          displayName: displayNameParam,
          iconUrl: iconUrlParam,
        );

        return object;
      },
    ),
    TvProgram: obx_int.EntityDefinition<TvProgram>(
      model: _entities[7],
      toOneRelations: (TvProgram object) => [],
      toManyRelations: (TvProgram object) => {},
      getId: (TvProgram object) => object.id,
      setId: (TvProgram object, int id) {
        object.id = id;
      },
      objectToFB: (TvProgram object, fb.Builder fbb) {
        final channelXmlTvIdOffset = fbb.writeString(object.channelXmlTvId);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset =
            object.description == null
                ? null
                : fbb.writeString(object.description!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, channelXmlTvIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.startTime.millisecondsSinceEpoch);
        fbb.addInt64(5, object.stopTime.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final channelXmlTvIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final startTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final stopTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = TvProgram(
          id: idParam,
          channelXmlTvId: channelXmlTvIdParam,
          title: titleParam,
          description: descriptionParam,
          startTime: startTimeParam,
          stopTime: stopTimeParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[0],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[0].properties[1],
  );

  /// See [Category.playlist].
  static final playlist = obx.QueryRelationToOne<Category, Playlist>(
    _entities[0].properties[2],
  );

  /// See [Category.contentType].
  static final contentType = obx.QueryIntegerProperty<Category>(
    _entities[0].properties[3],
  );

  /// see [Category.channels]
  static final channels = obx.QueryBacklinkToMany<Channel, Category>(
    Channel_.category,
  );

  /// see [Category.movies]
  static final movies = obx.QueryBacklinkToMany<Movie, Category>(
    Movie_.category,
  );

  /// see [Category.tvSeries]
  static final tvSeries = obx.QueryBacklinkToMany<TvSeries, Category>(
    TvSeries_.category,
  );
}

/// [Channel] entity fields to define ObjectBox queries.
class Channel_ {
  /// See [Channel.id].
  static final id = obx.QueryIntegerProperty<Channel>(
    _entities[1].properties[0],
  );

  /// See [Channel.name].
  static final name = obx.QueryStringProperty<Channel>(
    _entities[1].properties[1],
  );

  /// See [Channel.streamUrl].
  static final streamUrl = obx.QueryStringProperty<Channel>(
    _entities[1].properties[2],
  );

  /// See [Channel.logoUrl].
  static final logoUrl = obx.QueryStringProperty<Channel>(
    _entities[1].properties[3],
  );

  /// See [Channel.epgId].
  static final epgId = obx.QueryStringProperty<Channel>(
    _entities[1].properties[4],
  );

  /// See [Channel.category].
  static final category = obx.QueryRelationToOne<Channel, Category>(
    _entities[1].properties[5],
  );

  /// See [Channel.playlist].
  static final playlist = obx.QueryRelationToOne<Channel, Playlist>(
    _entities[1].properties[6],
  );
}

/// [Playlist] entity fields to define ObjectBox queries.
class Playlist_ {
  /// See [Playlist.id].
  static final id = obx.QueryIntegerProperty<Playlist>(
    _entities[2].properties[0],
  );

  /// See [Playlist.name].
  static final name = obx.QueryStringProperty<Playlist>(
    _entities[2].properties[1],
  );

  /// See [Playlist.url].
  static final url = obx.QueryStringProperty<Playlist>(
    _entities[2].properties[2],
  );

  /// See [Playlist.username].
  static final username = obx.QueryStringProperty<Playlist>(
    _entities[2].properties[3],
  );

  /// See [Playlist.password].
  static final password = obx.QueryStringProperty<Playlist>(
    _entities[2].properties[4],
  );

  /// See [Playlist.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<Playlist>(
    _entities[2].properties[5],
  );

  /// See [Playlist.typeInt].
  static final typeInt = obx.QueryIntegerProperty<Playlist>(
    _entities[2].properties[6],
  );

  /// see [Playlist.channels]
  static final channels = obx.QueryBacklinkToMany<Channel, Playlist>(
    Channel_.playlist,
  );

  /// see [Playlist.categories]
  static final categories = obx.QueryBacklinkToMany<Category, Playlist>(
    Category_.playlist,
  );
}

/// [Movie] entity fields to define ObjectBox queries.
class Movie_ {
  /// See [Movie.id].
  static final id = obx.QueryIntegerProperty<Movie>(_entities[3].properties[0]);

  /// See [Movie.name].
  static final name = obx.QueryStringProperty<Movie>(
    _entities[3].properties[1],
  );

  /// See [Movie.streamUrl].
  static final streamUrl = obx.QueryStringProperty<Movie>(
    _entities[3].properties[2],
  );

  /// See [Movie.coverUrl].
  static final coverUrl = obx.QueryStringProperty<Movie>(
    _entities[3].properties[3],
  );

  /// See [Movie.description].
  static final description = obx.QueryStringProperty<Movie>(
    _entities[3].properties[4],
  );

  /// See [Movie.year].
  static final year = obx.QueryStringProperty<Movie>(
    _entities[3].properties[5],
  );

  /// See [Movie.duration].
  static final duration = obx.QueryStringProperty<Movie>(
    _entities[3].properties[6],
  );

  /// See [Movie.rating].
  static final rating = obx.QueryStringProperty<Movie>(
    _entities[3].properties[7],
  );

  /// See [Movie.streamId].
  static final streamId = obx.QueryStringProperty<Movie>(
    _entities[3].properties[8],
  );

  /// See [Movie.category].
  static final category = obx.QueryRelationToOne<Movie, Category>(
    _entities[3].properties[9],
  );

  /// See [Movie.playlist].
  static final playlist = obx.QueryRelationToOne<Movie, Playlist>(
    _entities[3].properties[10],
  );

  /// See [Movie.tmdbId].
  static final tmdbId = obx.QueryStringProperty<Movie>(
    _entities[3].properties[11],
  );

  /// See [Movie.trailer].
  static final trailer = obx.QueryStringProperty<Movie>(
    _entities[3].properties[12],
  );

  /// See [Movie.added].
  static final added = obx.QueryStringProperty<Movie>(
    _entities[3].properties[13],
  );

  /// See [Movie.rating_5based].
  static final rating_5based = obx.QueryDoubleProperty<Movie>(
    _entities[3].properties[14],
  );

  /// See [Movie.posterUrl].
  static final posterUrl = obx.QueryStringProperty<Movie>(
    _entities[3].properties[15],
  );

  /// See [Movie.backdropUrl].
  static final backdropUrl = obx.QueryStringProperty<Movie>(
    _entities[3].properties[16],
  );

  /// See [Movie.myList].
  static final myList = obx.QueryIntegerProperty<Movie>(
    _entities[3].properties[17],
  );

  /// See [Movie.isFeatured].
  static final isFeatured = obx.QueryBooleanProperty<Movie>(
    _entities[3].properties[18],
  );

  /// See [Movie.featuredPosterUrl].
  static final featuredPosterUrl = obx.QueryStringProperty<Movie>(
    _entities[3].properties[19],
  );
}

/// [TvEpisode] entity fields to define ObjectBox queries.
class TvEpisode_ {
  /// See [TvEpisode.id].
  static final id = obx.QueryIntegerProperty<TvEpisode>(
    _entities[4].properties[0],
  );

  /// See [TvEpisode.title].
  static final title = obx.QueryStringProperty<TvEpisode>(
    _entities[4].properties[1],
  );

  /// See [TvEpisode.streamUrl].
  static final streamUrl = obx.QueryStringProperty<TvEpisode>(
    _entities[4].properties[2],
  );

  /// See [TvEpisode.seasonNumber].
  static final seasonNumber = obx.QueryIntegerProperty<TvEpisode>(
    _entities[4].properties[3],
  );

  /// See [TvEpisode.episodeNumber].
  static final episodeNumber = obx.QueryIntegerProperty<TvEpisode>(
    _entities[4].properties[4],
  );

  /// See [TvEpisode.coverUrl].
  static final coverUrl = obx.QueryStringProperty<TvEpisode>(
    _entities[4].properties[5],
  );

  /// See [TvEpisode.description].
  static final description = obx.QueryStringProperty<TvEpisode>(
    _entities[4].properties[6],
  );

  /// See [TvEpisode.duration].
  static final duration = obx.QueryStringProperty<TvEpisode>(
    _entities[4].properties[7],
  );

  /// See [TvEpisode.streamId].
  static final streamId = obx.QueryStringProperty<TvEpisode>(
    _entities[4].properties[8],
  );

  /// See [TvEpisode.series].
  static final series = obx.QueryRelationToOne<TvEpisode, TvSeries>(
    _entities[4].properties[9],
  );
}

/// [TvSeries] entity fields to define ObjectBox queries.
class TvSeries_ {
  /// See [TvSeries.id].
  static final id = obx.QueryIntegerProperty<TvSeries>(
    _entities[5].properties[0],
  );

  /// See [TvSeries.name].
  static final name = obx.QueryStringProperty<TvSeries>(
    _entities[5].properties[1],
  );

  /// See [TvSeries.coverUrl].
  static final coverUrl = obx.QueryStringProperty<TvSeries>(
    _entities[5].properties[2],
  );

  /// See [TvSeries.description].
  static final description = obx.QueryStringProperty<TvSeries>(
    _entities[5].properties[3],
  );

  /// See [TvSeries.year].
  static final year = obx.QueryStringProperty<TvSeries>(
    _entities[5].properties[4],
  );

  /// See [TvSeries.rating].
  static final rating = obx.QueryStringProperty<TvSeries>(
    _entities[5].properties[5],
  );

  /// See [TvSeries.seriesId].
  static final seriesId = obx.QueryStringProperty<TvSeries>(
    _entities[5].properties[6],
  );

  /// See [TvSeries.category].
  static final category = obx.QueryRelationToOne<TvSeries, Category>(
    _entities[5].properties[7],
  );

  /// See [TvSeries.playlist].
  static final playlist = obx.QueryRelationToOne<TvSeries, Playlist>(
    _entities[5].properties[8],
  );

  /// See [TvSeries.tmdbId].
  static final tmdbId = obx.QueryStringProperty<TvSeries>(
    _entities[5].properties[9],
  );

  /// See [TvSeries.myList].
  static final myList = obx.QueryIntegerProperty<TvSeries>(
    _entities[5].properties[10],
  );

  /// See [TvSeries.isFeatured].
  static final isFeatured = obx.QueryBooleanProperty<TvSeries>(
    _entities[5].properties[11],
  );

  /// See [TvSeries.featuredPosterUrl].
  static final featuredPosterUrl = obx.QueryStringProperty<TvSeries>(
    _entities[5].properties[12],
  );

  /// see [TvSeries.episodes]
  static final episodes = obx.QueryBacklinkToMany<TvEpisode, TvSeries>(
    TvEpisode_.series,
  );
}

/// [EpgChannelInfo] entity fields to define ObjectBox queries.
class EpgChannelInfo_ {
  /// See [EpgChannelInfo.id].
  static final id = obx.QueryIntegerProperty<EpgChannelInfo>(
    _entities[6].properties[0],
  );

  /// See [EpgChannelInfo.xmlTvId].
  static final xmlTvId = obx.QueryStringProperty<EpgChannelInfo>(
    _entities[6].properties[1],
  );

  /// See [EpgChannelInfo.displayName].
  static final displayName = obx.QueryStringProperty<EpgChannelInfo>(
    _entities[6].properties[2],
  );

  /// See [EpgChannelInfo.iconUrl].
  static final iconUrl = obx.QueryStringProperty<EpgChannelInfo>(
    _entities[6].properties[3],
  );
}

/// [TvProgram] entity fields to define ObjectBox queries.
class TvProgram_ {
  /// See [TvProgram.id].
  static final id = obx.QueryIntegerProperty<TvProgram>(
    _entities[7].properties[0],
  );

  /// See [TvProgram.channelXmlTvId].
  static final channelXmlTvId = obx.QueryStringProperty<TvProgram>(
    _entities[7].properties[1],
  );

  /// See [TvProgram.title].
  static final title = obx.QueryStringProperty<TvProgram>(
    _entities[7].properties[2],
  );

  /// See [TvProgram.description].
  static final description = obx.QueryStringProperty<TvProgram>(
    _entities[7].properties[3],
  );

  /// See [TvProgram.startTime].
  static final startTime = obx.QueryDateProperty<TvProgram>(
    _entities[7].properties[4],
  );

  /// See [TvProgram.stopTime].
  static final stopTime = obx.QueryDateProperty<TvProgram>(
    _entities[7].properties[5],
  );
}
